services:
  # Backend FastAPI Service
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend:/app  # Mount backend code for live reloading
      - ./data:/data  # Mount data directory for streaming history files
      - /app/__pycache__  # Prevent local pycache from overwriting container's
    env_file:
      - .env
    depends_on:
      - db

  # Frontend React Service
  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevents local node_modules from overwriting container's
    environment:
      - CHOKIDAR_USEPOLLING=true # Helps with file change detection in Docker
    stdin_open: true # Required for Create React App dev server
    tty: true

  # PostgreSQL Database Service
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  # pgAdmin 4 Database GUI
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data: