name: spotify-listening-intelligence

services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend:/app
      - ./data:/data
      - /app/__pycache__
    env_file:
      - .env
    depends_on:
      - spotify-listening-intelligence-db

  # Frontend React Service
  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  # PostgreSQL Database Service
  spotify-listening-intelligence-db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  # pgAdmin 4 Database GUI
  spotify-listening-intelligence-pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - spotify-listening-intelligence-db

volumes:
  postgres_data:
  pgadmin_data: